version: '3.7'
services:
#  queue:
#    image: redis:6.0.5
#    ports:
#      - "6379:6379"
#    volumes:
#      - queue-data:/data

  mysql:
    image: mariadb:10.4.13
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE}
    volumes:
      - mysql:/var/lib/mysql


#  es:
#    image: elasticsearch:7.9.3
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    volumes:
#      - es:/usr/share/elasticsearch/data
#    environment:
#      - bootstrap.memory_lock=true
#      - 'discovery.type=single-node'
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

volumes:
#  es:
#    name: hied-es
  mysql:
    name: classting-mysql
#  queue-data:
#    name: hied-redis
